name: pase_de_lista
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:        # ğŸ‘ˆ nombre correcto del paquete
    sdk: flutter                # ğŸ‘ˆ va con sdk, no versiÃ³n manual
  intl: ^0.20.2
  pdf: ^3.11.0
  flutter_secure_storage: ^9.0.0
  printing: ^5.13.4
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  file_picker: ^8.0.0
  excel: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0          # ğŸ‘ˆ aquÃ­ va, en dev_dependencies
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_1024.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_1024.png
    - assets/images/logo_cetis31.png
